// This file was automatically generated. DO NOT EDIT.
// If you have any remark or suggestion do not hesitate to open an issue.

package scalewaysdkgo

import (
	_ "github.com/scaleway/scaleway-sdk-go/api/account/v2"
	_ "github.com/scaleway/scaleway-sdk-go/api/account/v3"
	_ "github.com/scaleway/scaleway-sdk-go/api/applesilicon/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/billing/v2alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/cockpit/v1beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/container/v1beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/documentdb/v1beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/function/v1beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/instance/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/iot/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/ipam/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/ipam/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/ipfs/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/marketplace/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/marketplace/v2"
	_ "github.com/scaleway/scaleway-sdk-go/api/mnq/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/mnq/v1beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/registry/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/test/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/tem/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/webhosting/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/baremetal/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/block/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/domain/v2beta1"
	_ "github.com/scaleway/scaleway-sdk-go/api/flexibleip/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/iam/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/k8s/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/lb/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/rdb/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/redis/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/secret/v1alpha1"
	_ "github.com/scaleway/scaleway-sdk-go/api/vpc/v2"
	_ "github.com/scaleway/scaleway-sdk-go/api/vpcgw/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/vpc/v1"
	_ "github.com/scaleway/scaleway-sdk-go/api/std"
)
